# Generated by Django 3.2.12 on 2023-11-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balanço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=30)),
                ('data', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos/despesas')),
                ('tipo', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Moradia', 'Moradia'), ('Filhos', 'Filhos'), ('Comunicação', 'Comunicação'), ('Saúde', 'Saúde'), ('Outros', 'Outros'), ('Despesa recorrente', 'Despesa recorrente')], max_length=255)),
                ('balanço', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finapp.balanço')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=40)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=15)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos/receitas')),
                ('balanço', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finapp.balanço')),
            ],
        ),
        migrations.CreateModel(
            name='HistóricoBalanço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanço', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finapp.balanço')),
                ('despesas', models.ManyToManyField(to='finapp.Despesa')),
                ('receitas', models.ManyToManyField(to='finapp.Receita')),
            ],
        ),
        migrations.AddField(
            model_name='balanço',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finapp.usuario'),
        ),
    ]
